[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database = "hwabi"
pool_size = 5

[[worlds]]
id = 0
name = "Scania"
description = "Welcome to Hwabi"
channels = 4
state = 0
event_exp = 0
event_drop = 0
character_creation_blocked = false